import helpers
import asyncio

tests = [
    "https://www.youtube.com/watch?v=EwXsiXTzXLk",
    "https://www.youtube.com/watch?v=c96uOVJk-8g",
    "https://www.youtube.com/watch?v=WPs67ap6AeY",
    "https://www.youtube.com/watch?v=kG5LCoRqGSI",
    "https://www.youtube.com/watch?v=x0NDkRxG0-8",
    "https://www.youtube.com/watch?v=QvqjVCWT_4g",
    "https://www.youtube.com/watch?v=nqvYFf-KGgk",
    "https://www.youtube.com/watch?v=7_Vpby3pthU",
    "https://www.youtube.com/watch?v=JVgoLeO_jVw",
    "https://www.youtube.com/watch?v=7N7UpVZSoyM",
    "https://www.youtube.com/watch?v=ZmbacJHSjPY",
    "https://www.youtube.com/watch?v=EOpOqr-OIIE",
    "https://www.youtube.com/watch?v=bSuftAN4vyk",
    "https://www.youtube.com/watch?v=I34-31nG9Lo",
    "https://www.youtube.com/watch?v=mKfzgL8VRV4",
    "https://www.youtube.com/watch?v=gq9tyF6oq3U",
    "https://www.youtube.com/watch?v=8LN-5YaxFmM",
    "https://www.youtube.com/watch?v=uW-TF_MTMYY",
    "https://www.youtube.com/watch?v=z8HJJ42YwYY",
    "https://www.youtube.com/watch?v=mFd_64Azzvo",
    "https://www.youtube.com/watch?v=x0HUyBlvp_c",
    "https://www.youtube.com/watch?v=04Q3Y2auW1Y",
    "https://www.youtube.com/watch?v=9G3jgJots3I",
    "https://www.youtube.com/watch?v=z69T1yUzn44",
    "https://www.youtube.com/watch?v=bmNdZ--o7JM",
    "https://www.youtube.com/watch?v=vN8hh7YFtvg",
    "https://www.youtube.com/watch?v=hVAr-uW76bo",
    "https://www.youtube.com/watch?v=-IgMUPZ_Ekc",
    "https://www.youtube.com/watch?v=TRvYphpkoXc",
    "https://www.youtube.com/watch?v=1qj8bkxPO9o",
    "https://www.youtube.com/watch?v=U76HoYWMBI0",
    "https://www.youtube.com/watch?v=og2hqbOD4OE",
    "https://www.youtube.com/watch?v=n6L-dt_DyIo",
    "https://www.youtube.com/watch?v=vJQa3HVw2q8",
    "https://www.youtube.com/watch?v=X_lIiZ_CX50",
    "https://www.youtube.com/watch?v=egBZKrJknwQ",
    "https://www.youtube.com/watch?v=1OLznYC-Tr8",
    "https://www.youtube.com/watch?v=vsOHNt24724",
    "https://www.youtube.com/watch?v=wwwyoqOavj8",
    "https://www.youtube.com/watch?v=OM3aKv1l_D4",
    "https://www.youtube.com/watch?v=09O4G6fAO54",
    "https://www.youtube.com/watch?v=3lNItwlLmnI",
    "https://www.youtube.com/watch?v=XniH6QAnLRw",
    "https://www.youtube.com/watch?v=DDsBHah-Rcw",
    "https://www.youtube.com/watch?v=6Yo8x9BAgRw",
    "https://www.youtube.com/watch?v=kNX6LqLOQww",
    "https://www.youtube.com/watch?v=i_62o6Vj8LA",
    "https://www.youtube.com/watch?v=wQWGLPxga6A",
    "https://www.youtube.com/watch?v=0fip8q3piBA",
    "https://www.youtube.com/watch?v=gRq5wP6FjIw",
    "https://www.youtube.com/watch?v=5ZZxysTW-N4",
    "https://www.youtube.com/watch?v=8DUrjs8Z0ZE",
    "https://www.youtube.com/watch?v=Xb4czQnm-yg",
    "https://www.youtube.com/watch?v=TeRxsGUPXb8",
    "https://www.youtube.com/watch?v=QuV2dI-Fpwo",
    "https://www.youtube.com/watch?v=XX8ir96oP6w",
    "https://www.youtube.com/watch?v=sidQ9_uiB_0",
    "https://www.youtube.com/watch?v=rausYiL8qo4",
    "https://www.youtube.com/watch?v=5EIdWFVTAYA",
    "https://www.youtube.com/watch?v=Syar6Cstt-c",
    "https://www.youtube.com/watch?v=f1DLJb1NvH0",
    "https://www.youtube.com/watch?v=7LpYxzuPCEQ",
    "https://www.youtube.com/watch?v=3M7L10aLB_o",
    "https://www.youtube.com/watch?v=bqCTTaBkqYs",
    "https://www.youtube.com/watch?v=LQtW1K7D8eA",
    "https://www.youtube.com/watch?v=d97xXtB4UeA",
    "https://www.youtube.com/watch?v=Et6DrP03nQY",
    "https://www.youtube.com/watch?v=qE7ms2QFRQw",
    "https://www.youtube.com/watch?v=rnJYlQ_bVP4",
    "https://www.youtube.com/watch?v=gavhpOkrrV8",
    "https://www.youtube.com/watch?v=zVMsJInJxdo",
    "https://www.youtube.com/watch?v=lp7mg0YsVg4",
    "https://www.youtube.com/watch?v=gCSkWUnVf6Y",
    "https://www.youtube.com/watch?v=UyCgkaBIyAo",
    "https://www.youtube.com/watch?v=IQaR1KfEew0",
    "https://www.youtube.com/watch?v=o-NU0toADAw",
    "https://www.youtube.com/watch?v=ghXeZ8MAXng",
    "https://www.youtube.com/watch?v=T-APn7xt3NM",
    "https://www.youtube.com/watch?v=u0yUmWt4v_Q",
    "https://www.youtube.com/watch?v=mCdoJNnMDlM",
    "https://www.youtube.com/watch?v=UU1vZoOeGNE",
    "https://www.youtube.com/watch?v=ZUU30oNfiuI",
    "https://www.youtube.com/watch?v=TRHFnl7VLzU",
    "https://www.youtube.com/watch?v=PgAxibDmN_E",
    "https://www.youtube.com/watch?v=rwhDQZb0rG4",
    "https://www.youtube.com/watch?v=V55cVC94uKE",
]


async def main():
    tasks = [asyncio.create_task(helpers.fetch(test)) for test in tests]
    await asyncio.gather(*tasks)


asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
asyncio.run(main())
